import React from "react";

const LoveList = () => {
  const items = [
    "Your beautiful smile",
    "The way you hug",
    "The love surges you give me",
    "Your starry eyes",
    "You love playing",
    "Your family",
    "Your style",
    "You’re so hardworking and smart, I’m so proud of you!",
    "Your thrill for adventure",
    "Your love for the stars and the universe",
    "You're the best little spoon",
    "When you're the big spoon",
    "Your food taste",
    "Your music taste",
    "You never back down from going out to dinner",
    "You always put friends, family, and fun first",
    "My matcha princess",
    "The way you squeeze Dobby",
    "You are always interested in my hobbies",
    "Your kisses",
    "The way you hold my hands",
    "Your self-respect",
    "Your warmth",
    "Your silver jewelry",
    "Your red flower skirt",
    "Your love for my family",
    "Your love for anime",
    "Gon and Killua >>>",
    "You try to get to know my friends",
    "Your excitement for our surprise dates",
    "When you plan our monthly dinners",
    "ChiChaaaa boba",
    "Your love for the Flyers, and getting me into them",
    "Our time in Japan",
    "Our excitement to go back to Japan one day",
    "How good of a listener you are",
    "How analytical you are",
    "Gentle touch",
    "How you lotion me when my skin is dry",
    "When you laugh really hard",
    "Your gentle snore while sleeping",
    "Your honesty",
    "Your maturity",
    "Your Seattle surprise visit",
    "You love to go with the flow",
    "You find the beauty and fun in any activity",
    "Your meditation",
    "Journaling",
    "The Four Agreements",
    "The Mastery of Love",
    "Steve Lacy sing-off",
    "Your dance moves",
    "Bello!!!!",
    "Your eagerness to visit Vietnam",
    "All the reels you spam me with",
    "You squeeze lemon in my water",
    "You always remind me of my allergies when we’re out at dinner",
    "Your tree nut jokes",
    "The rice face masks we did together",
    "You let me hold your shopping bags",
    "Our Chinatown trips",
    "Your good morning texts",
    "Your tattoos and their resemblance to nature",
    "Your love for food",
    "How you motivate me every day to be better",
    "You being there for my family",
    "You hold back on eating guacamole for me (sometimes)",
    "Conveyor belt sushi",
    "Yummy Pho",
    "Your passion for community building",
    "Our FaceTimes this past summer",
    "Your storytelling, ESPECIALLY when you go into detail",
    "You let me use your skincare products",
    "We always go 50/50 down our food, tb to korean in japan",
    "Our bite of half the piece of food until theres none left contest",
    "Snow days with you",
    "When our souls touch",
    "You notice all the small things",
    "You listen to me rant",
    "Your love for shopping",
    "Mole on your middle finger right hand",
    "Two moles above your belly button",
    "Yellow kiwis",
    "When you lean your head on my shoulder on the train",
    "When you get a little mad at me on your period",
    "Your cooking",
    "When you eat my cooking",
    "Your back scratches",
    "Your hair",
    "How you fall asleep while I brush your hair",
    "You gave me my first-ever foot massage",
    "Stargazing",
    "You asking me out under a pink sky and Frank Ocean",
    "How you helped me decorate my room",
    "When you kick your feet all happy",
    "Our NYC trip to visit Shaine",
    "How good you are at Mario Kart",
    "Snow Lake",
    "How you wear my name on your bracelet, and yours on mine",
    "How easily you pick up games and sports"
  ];

  return (
    <div className="p-6 max-w-2xl mx-auto h-screen flex flex-col text-yellow-900">
      <h1 className="text-3xl font-bold mb-4">100 Things I Love About You ❤️</h1>
      <div className="overflow-y-auto flex-1 border p-4 rounded-lg shadow-md">
        <ol className="list-decimal pl-5">
          {items.map((item, index) => (
            <li key={index} className="text-lg mb-1">{item}</li>
          ))}
        </ol>
      </div>
    </div>
  );
};

export default LoveList;